[[MultiStepFormsAdapterConfiguration]]
== MultiStepFormsAdapterConfiguration

++++
 Options describing how an ServiceAdapter will make connections with external HTTP services.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[adapterAddress]]`adapterAddress`|`String`|-
|[[address]]`address`|`String`|-
|[[clientOptions]]`clientOptions`|`link:cheatsheets.adoc#WebClientOptions[WebClientOptions]`|
+++
Sets the Vert.x Web Client options of the Web client.
+++
|[[customHttpHeader]]`customHttpHeader`|`link:cheatsheets.adoc#CustomHttpHeader[CustomHttpHeader]`|
+++
Sets the header (name &amp; value) to be sent in every request to the services. If not set, it
 sends <code>Server-User-Agent=Knot.x</code> header
+++
|[[redis]]`redis`|`link:cheatsheets.adoc#RedisConfiguration[RedisConfiguration]`|-
|[[services]]`services`|`Array of link:cheatsheets.adoc#ServiceConfiguration[ServiceConfiguration]`|
+++
Sets the configuration of each service endpoint used by the adapter.
+++
|[[sessionAddress]]`sessionAddress`|`String`|-
|===
[[RedisConfiguration]]
== RedisConfiguration

++++
 Describes a physical details of HTTP service endpoint the ServiceAdapter will use.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[host]]`host`|`String`|-
|[[port]]`port`|`Number (int)`|-
|===
[[ServiceConfiguration]]
== ServiceConfiguration

++++
 Describes a physical details of HTTP service endpoint the ServiceAdapter will use.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[additionalHeaders]]`additionalHeaders`|`Json object`|
+++
Set the additional request headers (and values) to be send in each request
+++
|[[allowedRequestHeaders]]`allowedRequestHeaders`|`Array of String`|
+++
Sets the allowed requests headers that should be send to the service. The selected headers from
 the original client HTTP request are being send.
+++
|[[domain]]`domain`|`String`|
+++
Set the <code>domain</code> of the external service
+++
|[[path]]`path`|`String`|-
|[[port]]`port`|`Number (int)`|
+++
Sets the HTTP <code>port</code> the external service
+++
|[[queryParams]]`queryParams`|`Json object`|
+++
Set the additional request query parameters to be send in each request
+++
|===
